### ISSUE TITLE
Delete physical volume fails with 500 status code

### ISSUE THREAD

**Issue by sureshab** [kimchi-project/ginger#133]
Selected a pv which vg and executed delete api.

[root@zfwcec164 ~]# pvdisplay /dev/mapper/36005076802810d504800000000002ef2 
  --- Physical volume ---
  PV Name               /dev/mapper/36005076802810d504800000000002ef2
  VG Name               testvg3
  PV Size               1.00 GiB / not usable 4.00 MiB
  Allocatable           yes 
  PE Size               4.00 MiB
  Total PE              255
  Free PE               255
  Allocated PE          0
  PV UUID               rcnxbt-KQIS-lCbu-EbDy-K68N-K1QM-og4Wes
   
[root@zfwcec164 ~]# curl -k -i -u root -H "Content-Type: application/json" -H "Accept: application/json" -X DELETE 'https://127.0.0.1:8001/plugins/ginger/pvs/%2fdev%2fmapper%2f36005076802810d504800000000002ef2'
Enter host password for user 'root':
HTTP/1.1 500 Internal Server Error
{
  "reason":"GINPV00005E: Failed to delete PV",
  "code":"500 Internal Server Error"
}

**Comment by danielhb** [comment]
I'll have a crack at this

**Comment by danielhb** [comment]
The problem here is not that it will return 500 even if the volume doesn't exist (we return a 404 in this case) but also the error message is not informing why the operation failed. 

I'll fix both of these issues and send a patch to the ML.

**Comment by sureshab** [comment]
@danielhb 
yes, the problem is when the pv is assigned to a vg,, and we try delete on that pv....it fails. which is perfectly fine,,,but the error code should be 400/405 not 500. Reason is getting logged in wok-error.log.

**Comment by danielhb** [comment]
@sureshab hmmm ... perhaps the patch I've sent only fixed half of the problem .... I'll let you know when it's upstream, then I'll ask you to test it. Then we can assess if there's more work to be done.

**Comment by sureshab** [comment]
:+1:

**Comment by danielhb** [comment]
@sureshab can you please check is this issue can be fixed or if there's something else to be done?

**Comment by pkulkark** [comment]
@danielhb 
Hi, the issue is not fixed yet.

[root@zfwcec164 ~]# curl -k -u root -H "Content-Type: application/json" -H "Accept: application/json" -X DELETE 'https://127.0.0.1:8001/plugins/ginger/pvs/%2fdev%2fdasdb1'
{
  "reason":"GINPV00005E: Failed to delete PV",
  "code":"500 Internal Server Error"
} 
scenario: above pv is part of vg, so it fails to remove pv, which fine..but the error message and return code can be improved.

this is the o/p from pv remove:
[root@zfwcec164 ~]# pvremove /dev/dasdb1
  PV /dev/dasdb1 belongs to Volume Group newvg so please use vgreduce first.
  (If you are certain you need pvremove, then confirm by using --force twice.)

from backend we can pass the error message so the user is sure why it failed to remove.

**Comment by pkulkark** [comment]
I will be sending a patch for this
