### ISSUE TITLE
Administration page on load options gets reduced to limited option

### ISSUE THREAD

**Issue by rajatgupta21** [kimchi-project/ginger#143]
![admin_1 1](https://cloud.githubusercontent.com/assets/511072/12195090/c2a4a090-b61a-11e5-85de-d56c6e106da2.png)
![admin_1 2](https://cloud.githubusercontent.com/assets/511072/12195094/c81f69ba-b61a-11e5-8108-198b7ad398b4.png)

 Post login Administration page shows multiple options, later it reduces to only two options.
expected on load page should display only option which are valid for user.

**Comment by danielhb** [comment]
How can I reproduce this behavior? Do I need to refresh the same tab multiple tabs, logout/login in the interface ..... ?

**Comment by chandrureddy** [comment]
I guess, based on the platform this page will show options that are relevant. 
So for example on x86 case Power Options and SEP configuration doesn't make sense.
Similarly on s390x case Firmware Update, Power Options, Sensor Monitor and SEP configurations doesn't make sense at this point of time.

So I guess we can safely reject the defect saying "Expected Behavior".

**Comment by chandrureddy** [comment]
Also there was fix by Rajat self:
https://github.com/kimchi-project/ginger/commit/b579d7e88d4fef2ef933c12eaf402f6fafedbf7b

So please close this ticket.
