### ISSUE TITLE
Update an interface on tab "Administration" -> "Network Configuration" fails

### ISSUE THREAD

**Issue by pawankg** [kimchi-project/ginger#15]
Update an interface on tab "Administration" -> "Network Configuration" fails

Work environment:
[ network-scripts]$ cat /etc/fedora-release
Fedora release 21 (Twenty One)

Steps to reproduce:
1. Go to tab "Administration" -> "Network Configuration" fails
2. Pick any interface which can be editable
3. Change ip/netmask values and Save. Save succeeded at least for interface "lo" but when refreshed the page back, values are back to original (whatever before edit)
4. For other interface still I see edit option enabled but when try to save, save failed "The Server encountered an unexpected condition which prevented it from fulfilling the request."

What is the expected behavior ? Is interface update allowed and what all the cases it allowed ?

**Comment by papusagar83** [comment]
I addition 
 I am running kimchi-ginger https://9.152.151.63:8001/#tabs/host "mozilla firefox ESR 31.8.0 ESR".

As above mentioned that previous data occurs after refreshing the page.
But here i am unable to save the edited interface mask and IP.

![networkconfigurationissue](https://cloud.githubusercontent.com/assets/13309902/8717115/9c296c38-2bb5-11e5-9cb6-b86ed9e49fb1.PNG)

**Comment by danielhb** [comment]
The edit interface works here in my machine.

At first you can edit the interface to assume any value you want, but you're restricted in the ways you are when changing the IP address using the terminal (you can't have the same IP in the same network for example). The type of the device you're editing also interfere with the expected behavior.

The message "The Server encountered an unexpected condition which prevented it from fulfilling the request." means that an unexpected error occurred and the backend wasn't able to forward the error to the user interface. This is something that can be worked on if I can simulate the error. 

Can you provide more info, for example the type of interface it failed to edit (if it is an Ethernet card, wireless network card etc)?

**Comment by pawankg** [comment]
Hi Daniel, Thanks for your input. I tried updating interface on several machines, but I am still facing the same problems as I mentioned in issue #15. Below is something that I tried:

Steps to reproduce:
1. Go to tab "Administration" -> "Network Configuration"

2. Pick any interface which is editable. I tried updating IP for interface lo [IP 127.0.0.1 before updating].
![snap2](https://cloud.githubusercontent.com/assets/12508064/8951805/9fa5fd3e-35ee-11e5-82d4-70f4997053a7.png)

3. IP value changed to 127.0.0.2 and Saved. Updated IP [127.0.0.2] will be reflected on Kimchi UI.
![pic1](https://cloud.githubusercontent.com/assets/12508064/8951816/bebcbca8-35ee-11e5-835f-126d31a2d89a.png)

4. Refresh Kimchi, IP address will revert to previous value [127.0.0.1].
![snap2](https://cloud.githubusercontent.com/assets/12508064/8951824/d2935fb6-35ee-11e5-93bb-82aa1b5ffd8f.png)

It is not allowing to update other interfaces but I cannot see the error "The Server encountered an unexpected condition which prevented it from fulfilling the request." now while updating the interface.

**Comment by danielhb** [comment]
Sorry for the delay in answering

I'll try to replicate the same steps here. The IP went back to 127.0.0.1 because the backend failed into actually changing it to 127.0.0.2. Yes, it should warn the user of the error.

My machine is running F22 in a lenovo T430. I believe this is not so different from what you're running

**Comment by danielhb** [comment]
The code changed so much in these last 3 months that it's impossible to reproduce the same conditions anymore

Let me know if you're still have problems with the current network management implementation.

Thanks!
