### ISSUE TITLE
No message appears for editing Global Network Configuration

### ISSUE THREAD

**Issue by rajatgupta21** [kimchi-project/ginger#172]
Click Network→Global Network Configuration→Edit
Post editing message should appear for confirmation of action.

**Comment by danielhb** [comment]
Do you mean a message like "Do you confirm these changes?" before the edited changes are saved?

I don't believe the confirmation before editing is common as the confirmation before a delete action. Reason is that if you edited a wrong value you can most likely edit it again to the correct one, but when you delete there's no easy going back.

However I can see some use for this confirmation in this specific case due to the fact that editing the network might cut Ginger access from the host.

**Comment by chandrureddy** [comment]
Assign this to me, I will do for deletion of interface ie. confirm message before interface deletion.

**Comment by chandrureddy** [comment]
Issue fixed in the new implementation so please close this ticket
