### ISSUE TITLE
Network Bond UI page improvements

### ISSUE THREAD

**Issue by chandrureddy** [kimchi-project/ginger#176]
1. First of all alignment is mismatch
2. Second Advanced tab shows all the MI fields as red. I guess if not given these values it might be case that we can create still bond interface
3. For now we can disable Firewall Zone as this field with out proper back end code not makes very much sense.
<img width="807" alt="screen shot 2016-01-12 at 8 00 11 pm" src="https://cloud.githubusercontent.com/assets/10830725/12267004/11507d8c-b96c-11e5-932b-48c2900121c1.png">

**Comment by abhiramkulkarni** [comment]
Since i see bond related issues are raised here, putting here the summary of issues noticed.

1)Add Bond, Currenty automatic and manual mode is supported in backed. Automatic dhcp is displayed in selection instead of automatic.This is for ipv6
2)Given bond name, selected one slave, and mode balance-rr... GINNET0040E: Invalid bonding option parameter was the error message. Not clear what option is missing.
3)Monitoring interval, link up delay, link down delay is mandatory for bond creation? Also there is no option in UI to choose the values for this.
4)Monitoring interval, link up delay, link down delay is given manually in UI. Still the fields are displayed in red. Press apply it gets successfully created.
5)After successfully apply bond dialog should disappear..
6)Link Monitoring and Firewall should display default values when you try to edit the created bond.
7)Apply button should be disabled in general when all the mandatory parameters is not given and none of the fields should be in red, when apply button is enabled.
8)Apply bond successfull. Message shown is incorrect. successfull[object Object]


Let me know if its fine or any above issue need to be raised as separate issue.

**Comment by chandrureddy** [comment]
@abhiramkulkarni , second point mentioned is coming from back end. so we need to look into that.

**Comment by chandrureddy** [comment]
Please assign this ticket to me.

**Comment by abhiramkulkarni** [comment]
Working in latest upstreamed code
