### ISSUE TITLE
Is python-cheetah build dependency for ginger?

### ISSUE THREAD

**Issue by jay-katta** [kimchi-project/ginger#260]
I see that python-cheetah as listed as build dependency in ginger spec file.
But I do not see as dependency in readme document of ginger.

**Comment by alinefm** [comment]
python-cheetah is only needed by wok.

**Comment by danielhb** [comment]
"python-cheetah is only needed by wok."

I am not sure if that's the case. python-cheetah is a build requirement, not a regular dependency like pyparted (which I'll be removing since it's a dependency of gingerbase). To remove python-cheetah from the build requires tag we would need to test the build of Ginger in a environment without python-cheetah to see if it works.

Now, python-cheetah is a template engine and we have a lot of template files under ui/pages dir. So, at first, I believe we can't get rid of this build requirement. We need cheetah to process these templates.

@samhenri do you have any comments in this subject? I know that our UI build has changed quite a bit but I don't recall any change in the template processing.

**Comment by samhenri** [comment]
@danielhb Template engine is the same from old-ui

**Comment by alinefm** [comment]
Hi @danielhb 

The templates files are converted to true HTML file on runtime by Wok, on each request.
So there is no need to have it as dependency on any Wok plugin at all (runtime or build dep).

**Comment by danielhb** [comment]
Roger that @alinefm . Thanks for the explanation.

I'll remove python-cheetah from Ginger build dependencies.
