### ISSUE TITLE
Redesign "Global Network Configuration" UI

### ISSUE THREAD

**Issue by alinefm** [kimchi-project/ginger#299]
The current UI for "Global Network Configuration" is a mess!

![4321aee82868e015](https://cloud.githubusercontent.com/assets/4921718/14290337/0af2f32e-fb35-11e5-9040-9642b8877278.jpg)

1. The "Edit" and "Delete" icons should be used with a label explaining the actions
2. The "Edit" and "Delete" icons do not change the mouse cursor so there is no feedback the icons are clickable. 
3. When selection "Delete", the table entry is removed but no action is really performed. You need to go to Actions > Apply to have the changes applied.
4. When selecting "Edit", the table entry becomes a input box and 2 icons are displayed: the save icons and the delete icon. No icon will perform the action it is supposed to do - you need again to go to Actions > Apply to have the changes really saved.

Said that, I want to propose changes to this section, like described below:

```
- Global Network Configuration

Gateway: | < input box > |

Global DNS Addresses
| -------------------------------------------------- |
|  < input box 1 >         < delete icon > Delete    |
|  < input box 2 >         < delete icon > Delete    |
|  < input box 3 >         < delete icon > Delete    |
|                         < add icon>  Add new entry |
| -------------------------------------------------- |

| <save icon> Apply |
```

When selecting the "Apply" the action will get all the inputs and do the changes on server.
When selecting "Add new entry", a new row is added to the table with an input box to user enter a new DNS address.

All the buttons and input boxes shown on above mockup MUST follow the Wok style design.

**Comment by chandrureddy** [comment]
@alinefm 
The trouble here I see is with the REST API design. It is expecting both DNS and Gateway details whenever you want to apply changes on the system.

We can not have Apply directly underneath DNS section unless we separate both DNS and Gateway as different REST API calls. 

For sure there is a scope of improvement here but I guess some body can send RFC overall about the section and propose changes accordingly.

**Comment by samhenri** [comment]
@alinefm @chandrureddy Should we start developing the redesigned screen now or wait for a new REST API? I think with the new table library it will be really easy to change the layout if the DNS section is separated from the Gateway one day.

I don't think the Apply button should be below the table, as the other tables using Wok Datagrid, jQuery Bootgrid or Datatables.net all have the action buttons on top, unless we have a very large table like in System Modules and System Services that could be enhanced by buttons on the table head and footer.

Another question, since we are placing the Gateway section above the table, should we keep using half of the screen width or a full width table?

**Comment by samhenri** [comment]
@chandrureddy @alinefm I've made some improvements on the UI and here are some screenshots:
This is the default panel:
![global_network_1](https://cloud.githubusercontent.com/assets/326107/16598704/91832dc2-42d5-11e6-947e-a6afce1cd516.png)
-I've placed the Apply and Refresh buttons on the top for consistency and because the Apply action is linked to the DNS addresses that are configured in the table below.
-The text alignment may look slightly "off" compared to other tables but this was required to keep the text in the same position when the table cell becomes an input.

Adding a new entry:
![global_network_2](https://cloud.githubusercontent.com/assets/326107/16598703/9182c2ba-42d5-11e6-9c6b-400672ae9f5a.png)
-Let me know if you think I should always keep the "Add new entry" button below the newly added (but not saved) address. I think this way looks cleaner but it is easy to keep the "Add new entry" button all the times a new row is added.

Validation:
![global_network_4](https://cloud.githubusercontent.com/assets/326107/16598707/9184e8f6-42d5-11e6-8664-30b68b3e0095.png)
![global_network_5](https://cloud.githubusercontent.com/assets/326107/16598705/918446c6-42d5-11e6-9776-aa441bd14e21.png)
![global_network_6](https://cloud.githubusercontent.com/assets/326107/16598708/91853bb2-42d5-11e6-9ea3-2d8c221ac438.png)
![global_network_7](https://cloud.githubusercontent.com/assets/326107/16598706/9184e932-42d5-11e6-8b52-57bfc660f947.png)
-If the user attempts to add a new address or edit an address with an existing value, even if the table data is not saved, the "Save" button will be disabled. However, the user can still workaround the validation and "reorder" the DNS addresses like this:
![global_network_8](https://cloud.githubusercontent.com/assets/326107/16598996/dcddbe9e-42d6-11e6-82a7-f6e7f546a202.png)

I'm currently working on the Refresh and Apply actions. Do you think we should add a wok.confirm() dialog on the Refresh button if the user has added or edited the table?

**Comment by samhenri** [comment]
Another question: Should this panel have a height limit and fixed headers? If yes, how many lines should I display on the visible scroll-able area then?

**Comment by chandrureddy** [comment]
@samhenri 
Screens looks great to give user feeling that both gateway and DNS entries are together when it comes to apply.

So overall I liked your proposal. One suggestion could be at any point of time user should not be allowed to edit more than one record to keep it simple from the user point of view.

let us say : 
1. user clicked new record and then user also tried to click one of the existing record,  we can simply take of the new record. 
1. user clicked existing record and trying to click another record we should ask for save if any changes for the first record and then allow editing or deletion of second record.

I guess for now we can allow showing of max 5 DNA entries on the screen. But this limitation could away once we have left pane implementation.

**Comment by samhenri** [comment]
@chandrureddy I like this idea as it would simplify field validation. I will update and send a patch to the ML today.
