### ISSUE TITLE
Ginger spec file is restarting Wokd service twice

### ISSUE THREAD

**Issue by Truja** [kimchi-project/ginger#334]
With latest changes in Ginger rpm spec file if the package is installed or updated, it is going to restart Wokd service twice.

This issue has the following goals:
- check rpm packaging best practices for Fedora;
- check deb packaging best practices for Ubuntu;
- adapt rpm/deb packages accordingly;
- start the process to push the packages to those distros

You can assign this ticket for me

**Comment by ramonmedeiros** [comment]
Hi @Truja,

what about the  discussion of add a posttrans that checks for this issue: https://github.com/kimchi-project/ginger/commit/a4eb2b65ddf2c0fe141cd13d22df29d98dde4a30

Do you want to add this in this task?

**Comment by ramonmedeiros** [comment]
Seeing ginger.spec, i see some trouble:

Using absolute path instead of macros:
All paths must use macros.

Reference to macros at Changelog:
No macro(%files, %setup) should be written there

Systemd: 
A few kind of services can be started on installation, but, all packages can be restarted on upgrade IF the old service is running. More detailed information here:
https://fedoraproject.org/wiki/Packaging:DefaultServices
https://fedoraproject.org/wiki/Packaging:Scriptlets?rd=Packaging:ScriptletSnippets#Systemd

Other sources:
https://fedoraproject.org/wiki/Packaging:Guidelines

**Comment by ramonmedeiros** [comment]
One more issue from rpmlint:
Use tabs instead of spaces

**Comment by danielhb** [comment]
@Truja can you see if the issue is fixed?
