### ISSUE TITLE
Missing package dependancies in spec files

### ISSUE THREAD

**Issue by chandrureddy** [kimchi-project/ginger#38]
Missing package 'python-magic' dependancy in spec files.

The following files should reflect
1. ginger.spec.in
2. contrib/DEBIAN/control.in
3. README

**Comment by danielhb** [comment]
Yeah ... I would be surprised if this were the only dependency missing in the spec files and docs. We always assumed that Kimchi was installed, together with all its dependencies. We'll now run using WoK. This kind of issue will surely happen.

It'll be easier when we separate wok+kimchi+ginger-base into their own repos. Then we can easily install only wok + ginger-base + ginger and see what happens.

**Comment by chandrureddy** [comment]
python-netaddr is another one !!!

**Comment by danielhb** [comment]
Feel free to use this github entry to report the missing packages you find. It'll be easier to patch it up later

**Comment by pvital** [comment]
Since Wok is a required dependency for Ginger and a Wok already installs a package that is common between Ginger and Wok, it's not necessary to add the dependency in Ginger's list.
 
However, python-magic is a required dependency for Kimchi, not Wok. Since it's possible run Wok+Ginger only we need add python-magic in the list of required dependencies on ginger spec and deb files.

**Comment by chandrureddy** [comment]
python-ethtool

**Comment by danielhb** [comment]
There will probably be more dependencies missing now what we're officially independent of Kimchi. But let's close this bug and open new ones for the other missing dependencies.

Thanks, @chandrureddy !
