### ISSUE TITLE
service disapear after stopping it at opensuse 42.1

### ISSUE THREAD

**Issue by ramonmedeiros** [kimchi-project/ginger#414]
Go to system service administration
Stop a service
Reload page

Did not see it anymore

**Comment by sureshab** [comment]
Hi, 
this issue is still valid for services which are not enabled.
Steps to reproduce -
select a service and disable it using - systemctl disable <service name>
go to - System Services in wok UI and stop that service - reload the page.
I tried it for openvswitch and sshd.

@ramonmedeiros or @danielhb  could you please confirm and reopen if its valid?

**Comment by ramonmedeiros** [comment]
Did not reproduced here.

Steps:
Go to System Services UI
Run: systemctl disable <service>
Pressed F5
After that, Service is listed at inactive

I'm running Fedora 24

**Comment by sureshab** [comment]
I tested on Fedora and KVM for IBM z systems:

1) sshd is active and running

$# systemctl status sshd
● sshd.service - OpenSSH server daemon
   Loaded: loaded (/usr/lib/systemd/system/sshd.service; disabled; vendor preset: enabled)
   **Active: active (running)** since Mon 2016-11-07 09:27:30 CET; 7s ago
     Docs: man:sshd(8)
           man:sshd_config(5)
 Main PID: 81688 (sshd)
   CGroup: /system.slice/sshd.service
           └─81688 /usr/sbin/sshd -D

Nov 07 09:27:30 zfwcec164 systemd[1]: Started OpenSSH server daemon.
Nov 07 09:27:30 zfwcec164 systemd[1]: Starting OpenSSH server daemon...
Nov 07 09:27:30 zfwcec164 sshd[81688]: Server listening on 0.0.0.0 port 22.
Nov 07 09:27:30 zfwcec164 sshd[81688]: Server listening on :: port 22.

2) its disabled
$# systemctl is-enabled sshd
disabled


3) wok gui listing sshd service

![screenshot from 2016-11-07 13-58-58](https://cloud.githubusercontent.com/assets/12499230/20067559/a4993ee2-a53b-11e6-9772-2a3cb0edb3a2.png)

4) select "Stop" action:
![screenshot from 2016-11-07 13-59-08](https://cloud.githubusercontent.com/assets/12499230/20067586/c3c71e9c-a53b-11e6-8dc0-e9fba0415c9c.png)

5) UI displays success message
![screenshot from 2016-11-07 13-59-14](https://cloud.githubusercontent.com/assets/12499230/20067602/d53b5d0a-a53b-11e6-9add-317bb6285c1d.png)

6) confirming status from command line:
$# systemctl status sshd
● sshd.service - OpenSSH server daemon
   Loaded: loaded (/usr/lib/systemd/system/sshd.service; disabled; vendor preset: enabled)
   Active: **inactive (dead)**
     Docs: man:sshd(8)
           man:sshd_config(5)

Nov 07 09:26:27 zfwcec164 systemd[1]: Stopping OpenSSH server daemon...
Nov 07 09:26:27 zfwcec164 sshd[54761]: Received signal 15; terminating.
Nov 07 09:26:27 zfwcec164 systemd[1]: Stopped OpenSSH server daemon.
Nov 07 09:27:30 zfwcec164 systemd[1]: Started OpenSSH server daemon.
Nov 07 09:27:30 zfwcec164 systemd[1]: Starting OpenSSH server daemon...
Nov 07 09:27:30 zfwcec164 sshd[81688]: Server listening on 0.0.0.0 port 22.
Nov 07 09:27:30 zfwcec164 sshd[81688]: Server listening on :: port 22.
Nov 07 09:28:48 zfwcec164 sshd[81688]: Received signal 15; terminating.
Nov 07 09:28:48 zfwcec164 systemd[1]: Stopping OpenSSH server daemon...
Nov 07 09:28:48 zfwcec164 systemd[1]: Stopped OpenSSH server daemon.


7) Now reload page and look for sshd

![screenshot from 2016-11-07 13-59-31](https://cloud.githubusercontent.com/assets/12499230/20067648/0227fc4c-a53c-11e6-85bc-86cf3108ebc4.png)

It disappeared from list.

Could you please verify with sshd?

**Comment by danielhb** [comment]
I can say that sshd isn't being shown here. Here's the output in the terminal:

``` 
[danielhb@arthas kimchi]$ sudo systemctl status sshd
[sudo] password for danielhb: 
● sshd.service - OpenSSH server daemon
   Loaded: loaded (/usr/lib/systemd/system/sshd.service; disabled; vendor preset: disa
   Active: inactive (dead)
     Docs: man:sshd(8)
           man:sshd_config(5)
[danielhb@arthas kimchi]$
```

Same thing with openvswitch:
```
[danielhb@arthas kimchi]$ sudo systemctl status openvswitch
● openvswitch.service - Open vSwitch
   Loaded: loaded (/usr/lib/systemd/system/openvswitch.service; disabled; vendor prese
   Active: inactive (dead)
[danielhb@arthas kimchi]$ 

```

This has been tested in a Fedora 24 x86_64.

@ramonmedeiros please take a look into how the backend is retrieving the service list and why these services are being left out of it.

**Comment by ramonmedeiros** [comment]
Hi @sureshab, just reproduced. But, i only saw this environment with sshd. Maybe there is a category for services to have this behaviour. WIth other services, like my VPN manager, i was able to turn it off and see it at my services list as inactive.

I will spend more time understanding this. Thanks for all information.

**Comment by sureshab** [comment]
thanks @ramonmedeiros . latest fix is working fine.
