### ISSUE TITLE
[next] Proposing changes to interfaces 

### ISSUE THREAD

**Issue by jay-katta** [kimchi-project/ginger#53]
Hi,
    The current interfaces (resource) is listing details as below -
curl -k -u jkatta:jj4e9wig -H "Content-Type: application/json" -H "Accept: application/json" 'https://127.0.0.1:8001/plugins/giger/network/interfaces/enp0s25'
{
  "status":"active",
  "name":"enp0s25",
  "editable":false,
  "ipaddr":"9.x.y.z",
  "netmask":"255.255.255.0",
  "type":"nic"
}

I would like to propose following two changes
1. Here status being derived from /sys/class/net/enp0s25/carrier. 
Instead this we can derive from /sys/class/net/enp0s25/operstate.
2. We can have mac address in the list.
can derive from /sys/class/net/enp0s25/address

**Comment by danielhb** [comment]
"1. Here status being derived from /sys/class/net/enp0s25/carrier. 
Instead this we can derive from /sys/class/net/enp0s25/operstate."

And what's the advantage of using operstate instead of carrier?

"2. We can have mac address in the list.
can derive from /sys/class/net/enp0s25/address"

Fine by me

**Comment by danielhb** [comment]
@jay-katta , I believe this change is upstream already, right?

**Comment by danielhb** [comment]
Nvm just saw that the patch is still in the ML

Let me know if the patch works for Ubuntu too.

**Comment by jay-katta** [comment]
I have tested this patch on Ubuntu

**Comment by danielhb** [comment]
Issue fixed in master/next branches
